version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    environment:
      FLASK_DEBUG: "on"
      FLASK_ENV: development
      FLASK_APP: ./app/main.py
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
    # for hot code reloading
    volumes: ['./app:/app/app', './temp:/app/temp']
  worker:
    build:
      context: ./celery
    depends_on:
      - redis
    volumes: ['./celery:/queue', './temp:/temp', './src:/queue/src', './models:/queue/models']
  flower:
    image: mher/flower
    command: ['celery', '--broker=redis://redis:6379/0', 'flower', '--port=5555']
    ports:
      - "5555:5555"
    depends_on:
      - redis
  redis:
    image: redis